#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=2.0..\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend http-in
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 263314-web-01 52.3.243.191:80:80
        server 263314-web-02 54.144.143.87:80
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
