#!/usr/bin/env bash
# configures Nginx so that its HTTP response contains a custom header

# Add HAProxy PPA
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy=2.0.\*
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy

# Configure HAProxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 263314-web-01 52.3.243.191:80 check\n\tserver 263314-web-02 54.144.143.87:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
